### PR TITLE
Typo-Fix in the ChainUserProvider

### PR DESCRIPTION
**Pull request by KhorneHoly**
Hi,

found this bug as I wanted to integrate the JWTAuthenticator in a ChainAuthenticator. It fixes the issue #971.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Good catch, thanks @KhorneHoly.

**Comment by silverbackdan** [comment]
Hi @chalasr and @KhorneHoly 

This does not work for me and I believe the fix is not correct.

My solution that prevents the error is below. I'll open a PR.

```
                 if ($provider instanceof PayloadAwareUserProviderInterface) {
                        if (method_exists($provider, 'loadUserByIdentifierAndPayload')) {
                            return $provider->loadUserByIdentifierAndPayload($identity, $payload);
                        } else {
                            return $provider->loadUserByUsernameAndPayload($identity, $payload);
                        }
                    }
```

**Comment by silverbackdan** [comment]
Sorry, if you were pinged for my previous comment this is working and I was requiring `dev-master` not `2.x-dev`

See issue https://github.com/lexik/LexikJWTAuthenticationBundle/issues/971 which can be closed too.

**Comment by chalasr** [comment]
Thanks for confirming @silverbackdan. I will draft a release next week.

**Pull request merged**
