### PR TITLE
Update 3-functional-testing.md

### PR DESCRIPTION
**Pull request by ro0NL**

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
👌

**Comment by ro0NL** [comment]
@chalasr can you tick this off my list for me?  :grimacing:

**Comment by chalasr** [comment]
I'm on vacation (colombia), back in 10 days :)

**Comment by chalasr** [comment]
Merged in 0db5a232773e11a571ae73cc592bc60fd57121b2. Thanks Roland

**Pull request closed without merging**
