### PR TITLE
Removed deprecated SecurityContext in favour of TokenStorage for Symfony 2.6

### PR DESCRIPTION
**Pull request by kinncj**
This PR provides support for Symfony >= 2.6
If accepted, this must be tagged to not BC Symfony < 2.6

### CODE REVIEW

**Comment by slashfan** [comment]
Hi,

Thanks but merging this PR will make future fixes and features unavailable to symfony < 2.6 and we intend to support symfony 2.3 until its official end of support.

Would there be a way to support both 2.3 and 2.6+ ? Maybe testing symfony version in the extension class or in a compiler pass.

**Comment by kinncj** [comment]
You can tag for 2.6+ OR maybe :
- check in a compiler pass
-- If 2.6+, inject the one that uses the new Interface
-- Otherwise, the old one.

**Comment by slashfan** [comment]
Exactly. Would you have the time to modify the PR ?

**Comment by kinncj** [comment]
I can plan for the weekend, not now.

**Comment by guillaumek** [comment]
+1

**Comment by ifdattic** [comment]
+1

**Comment by slashfan** [comment]
Closing this PR (resolved by #70).

**Pull request closed without merging**
