### PR TITLE
Fix encryption

### PR DESCRIPTION
**Pull request by CvekCoding**
For explanation see https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1209

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for the great report and the PR. I think this has been fixed in #1214 (+ patch on web-token's library) so I'm closing.

**Comment by SCIF** [comment]
Hi @chalasr , 

But the problem is still there in 2.x branch so could you please consider this issue as relevant? May be backport a proper solution required. I have a fresh install of symfony 7.x with this bundle of version 2.20.3. Using of web-token is breaking because of this issue

**Comment by chalasr** [comment]
👋 @SCIF 
The fix has been [backported](https://github.com/lexik/LexikJWTAuthenticationBundle/commit/60770f1fb9ec0b8b0f27a0ee9e2bf441ca4a1db9) but not tagged yet! Expect 2.20.4 to be released tomorrow

**Comment by SCIF** [comment]
Hi @chalasr ,

Just a courtesy reminder :)

**Pull request closed without merging**
