### PR TITLE
Compatibility php 5.3

### PR DESCRIPTION
**Pull request by fconte**
A few small changes to make compatible code with PHP 5.3

### CODE REVIEW

**Comment by chalasr** [comment]
Hello @fconte,

Thank's for your work.
Even it could be easy to make the changes, I'm not sure that is a direction where this bundle wants to go.

@slashfan What do you think?

**Comment by chalasr** [comment]
@fconte Depending on the answer of slashfan, could you please add `5.3` to the .travis.yml versions in order to ensure that tests are green?

**Comment by tristanbes** [comment]
PHP `5.3` *and* `5.4` are EOL (end of life).

http://php.net/supported-versions.php

To me it's not the right move to add compatibility to those versions.

**Comment by chalasr** [comment]
@tristanbes Totally agreed.

@fconte Periods between new PHP releases are really shorter than 2 or 3 years ago, upgrade your server version must be too. It's time to move ...

I close this issue.

**Comment by fconte** [comment]
The [LTS version of Symfony supports php 5.3.9,](http://symfony.com/doc/2.8/reference/requirements.html) but I understand and agree that this is not the future.

**Comment by slashfan** [comment]
:+1: @chalasr PHP 5.3 and 5.4 are dead plus the library we use is compatible only php 5.5+.

**Pull request closed without merging**
