### PR TITLE
Support an attribute to answer yes when generating keys

### LINKED ISSUE #1073: Support an attribute to answer yes when generating keys
I wish to be able to use `lexik:jwt:generate-keypair` command with `--overwrite` and no promt, just generate it. I haven't found a way so far and a `-y` argument is pretty standard.

### PR DESCRIPTION
**Pull request by vasilvestre**
Fix https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1073

### CODE REVIEW

**Comment by chalasr** [comment]
@vasilvestre Do you plan to finish this PR at some point? Or are you looking for some help?

**Comment by vasilvestre** [comment]
> @vasilvestre Do you plan to finish this PR at some point? Or are you looking for some help?

I'm not sure the option is useful, passing -n does the same AFAIK. Should try first..
Wdyt ?

**Comment by chalasr** [comment]
If `--overwrite` already does the trick as it seems to do, I don't think we need a new option. At best a shortcut for this option (I thought it was the purpose of the linked issue)

**Comment by vasilvestre** [comment]
> If `--overwrite` already does the trick as it seems to do, I don't think we need a new option. At best a shortcut for this option (I thought it was the purpose of the linked issue)

I couldn't find the -n option at this moment. I'm closing it so

**Pull request closed without merging**
