### PR TITLE
JWTAuthenticator logic fix

### PR DESCRIPTION
**Pull request by ergnuor**
Am I right or just missing something? :)

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Woops! Nice catch :)

**Comment by chalasr** [comment]
Thank you @ergnuor.

**Comment by ergnuor** [comment]
> Thank you @ergnuor.

My pleasure :)

**Comment by chalasr** [comment]
Released in https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.12.3

**Comment by masonen** [comment]
Wo thanks @ergnuor this fix saved me a 2 hour headache

**Pull request merged**
