### PR TITLE
Clean 3.x

### PR DESCRIPTION
**Pull request by maxhelias**
- [x] Remove namshi/jose
- [x] Remove support < PHP8.1 & < Symfony 5.4
- [x] Support of PHPUnit 9.5
- [x] Update documentation
- [x] Create an upgrade file

### CODE REVIEW

**Comment by chalasr** [comment]
Great, thanks. Don't hesitate to tell me if you want some help regarding the test setup or anything, happy to do so.

**Comment by maxhelias** [comment]
@chalasr A merge of the 2.x into the 3.x would be nice to start. I'll let you know afterwards

**Comment by chalasr** [comment]
@maxhelias done in https://github.com/lexik/LexikJWTAuthenticationBundle/commit/3711d6fbe403606620c626dcb7211294fb1f776e

**Comment by maxhelias** [comment]
Thanks @chalasr !

It's difficult to fix the CI without cleaning the code base for symfony > 5.4. I can do it here and I can increase the compatibility with php too. Like  > 8.1 ? WDYT ?

**Comment by chalasr** [comment]
Yes, please go ahead :) Requiring PHP 8.1+ and Symfony 6.2+ is fine to me

**Comment by maxhelias** [comment]
@chalasr it's ready for a review 😄

**Comment by maxhelias** [comment]
@chalasr can you merge 2.x into 3.x that i rework this PR. Thanks

**Comment by chalasr** [comment]
@maxhelias done, rebase unlocked!

**Comment by maxhelias** [comment]
Thanks @chalasr ! Everything is good, I would like to have a first review. All that's left is to make the file UPGRADE-3.x.md

**Comment by chalasr** [comment]
Thanks a ton Max! You rock.

**Pull request merged**
