### PR TITLE
Drop PHP <7.1 and Symfony <5.3 support

### PR DESCRIPTION
**Pull request by herman-aka-wouter**
Fix for https://github.com/lexik/LexikJWTAuthenticationBundle/issues/996

For tag 3.x

### CODE REVIEW

**Comment by chalasr** [comment]
Awesome! Thanks for working on this @wouter-toppy.

**Comment by herman-aka-wouter** [comment]
@chalasr  still trying to test and fix the ci

**Comment by chalasr** [comment]
Looks good to me. I'll merge this very soon and send a follow-up PR to remove the whole security-guard integration.

**Comment by herman-aka-wouter** [comment]
@chalasr  tests completed. and on my part the issue is resolved

**Review by dmetzner — APPROVED** [review]

**Comment by herman-aka-wouter** [comment]
@chalasr any idea when i can expect this to be merged (and tagged in 3.x)
Dont know if you still have other pulls/issues you want to merge into the 3.x branch

the [JWTRefreshTokenBundle Pull](https://github.com/markitosgv/JWTRefreshTokenBundle/pull/338) is merged already, and hopefully gets a tag soon. 

after that this is the only thing that blocks our WMS upgrade to Symfony 6.1 and PHP 8.1. because we can't enable preloading because of the [original issue of this pull](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/996)

**Comment by chalasr** [comment]
Thank you @wouter-toppy.

**Comment by chalasr** [comment]
Note that I'm not going to tag 3.0 now, there is quite a lot of cleanup and work ongoing on 2.x before I can (should happen at some point by the end of the year). Of course meanwhile you can require the 3.x-dev version or some commit hash.

**Pull request merged**
