### PR TITLE
Fix dispatch signature on SF > 4.3

### PR DESCRIPTION
**Pull request by Webonaute**

### CODE REVIEW

**Comment by Webonaute** [comment]
This should resolve https://github.com/lexik/LexikJWTAuthenticationBundle/pull/669 as well.

**Comment by Webonaute** [comment]
@chalasr is it possible to release a fix for this?

**Comment by chalasr** [comment]
Apologies for the delay @Webonaute. 
We have an unrelated failure on the travis build which I'm looking into. Once I'm done, I will merge this one and release it right away.
Thank you for the patch.

**Comment by chalasr** [comment]
Thank you @Webonaute.

**Pull request merged**
