### PR TITLE
chore: add testrun for PHP 8.4. Fix implicit nullable parameter

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/lcobucci/jwt/blob/5.4.x/composer.json
Needs a release of  lcobucci/jwt 5.4 => DONE

https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

### CODE REVIEW

**Comment by tarlepp** [comment]
PHP 8.4 is released, so should this pull request be merged?

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks for the PR and sorry for the delay, it's Symfony 7.2+SymfonyCon time of the year. I'm going to merge and release asap probably on Saturday during the hackday

**Comment by Chris53897** [comment]
I wish you a good time at SymfonyCon

**Comment by vpominchuk** [comment]
Hey @chalasr,

I hope you had a good time at SymfonyCon
I was just wondering if you could find time to merge this PR.
Thanks.

**Comment by chalasr** [comment]
Thank you @Chris53897!

**Comment by mickverm** [comment]
@chalasr any chance these PHP 8.4 related changes could make it into a release? 😃

**Comment by mafftor** [comment]
Can It be released please? spamming deprecations...

**Comment by chalasr** [comment]
Sorry for the delay! Here you go https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v3.1.1

**Pull request merged**
