### PR TITLE
Invalid JWT Token description

### PR DESCRIPTION
**Pull request by DeveloperGeorg**
Hi there!
I met a problem, a little time ago and got exception message "Invalid JWT Token". The main problem was, that I had this error in prod only. So, I tried to find a reason.
My first thought was, that token was signed by different private keys. I wasted tons of time to find proofs, and when I find out, that this is the wrong idea, I was confused. After lots of time I find I reason: field "iat" claim identifies the future time. Exception wasn't clear, and I think, that it could be helpful to add this information to the message.

### CODE REVIEW

**Comment by DeveloperGeorg** [comment]
Hi, @lexikteam !
Are you still working on this pack?

**Comment by chalasr** [comment]
Hi @DeveloperGeorg , yes, this is maintained :)
I need some time to test a deep review to your change because I plan to revisit the design on this area. 
I'll do as soon as possible, and I can tell you that I agree with the motivation behind the patch you propose.

**Comment by fd6130** [comment]
+1 to this motivation. Because "Invalid JWT Token" just too generic and hard to debug when facing configuration error.

One of the case regarding to this error message #354

**Comment by darthf1** [comment]
Is it possible to include a better description for [this](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/LcobucciJWTEncoder.php#L52) as well? I got "Invalid JWT Token" on production only. But after a while I found that the caught error was something different:
```
Lcobucci\JWT\Signer\InvalidKeyProvided
It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
```

related to https://github.com/lexik/LexikJWTAuthenticationBundle/issues/354.

**Pull request closed without merging**
