### PR TITLE
Added new event when token is authenticated

### PR DESCRIPTION
**Pull request by gamringer**
With this, it is now possible to transpose elements from the JWT payload to the security context's authenticated token.

### CODE REVIEW

**Comment by gamringer** [comment]
Tests are failing with a deprecation notice from 2.6 : /

**Comment by slashfan** [comment]
Hi, don't worry we are on it ! Thanks for the PR by the way, it's a nice addition. We'll merge it as soon as we fix the builds on travis.

**Comment by slashfan** [comment]
Would you mind squashing your commits into a single one ? [See this](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit) for step by step instructions.

**Comment by gamringer** [comment]
I've squashed it all into 1 commit. Let me know if you need anything else.

**Comment by slashfan** [comment]
Nice thanks. We'll just have to check that injecting the event dispatcher in the JWTProvider doesn't cause any BC break before tagging it but it's ok to merge !

**Comment by 9orky** [comment]
@slashfan Hello, I just wanted to ask when you will release a new version of bundle (1.0.11 probably) including changes introduced by this PR? Possibility to get JWT itself is very helpful ;-)

**Comment by slashfan** [comment]
Hi, I'll try to tag it today. I'll let you know when it's done.

**Pull request merged**
