### PR TITLE
Add `allow_no_expiration` option to allow validating tokens without ttl

### PR DESCRIPTION
**Pull request by pluk77**
Fresh pull request to fix issue #889

### CODE REVIEW

**Comment by chalasr** [comment]
Looks good to me :) I may change the option name as it looks slightly complicated, but I'm ok with the implementation.
Thank you!

**Comment by pluk77** [comment]
Hello @chalasr . Any idea yet when you plan on approving or incorporating this PR into a new release?

**Comment by chalasr** [comment]
Thank you @pluk77.

**Comment by pluk77** [comment]
Thank you so much! This really helps my project.

**Pull request merged**
