### PR TITLE
Improve JWTProvider

### PR DESCRIPTION
**Pull request by JJK801**
HI,

This PR add the raw JWT into the Symfony Token, as we sometime need to decode it to fetch informations (iat, exp, etc...).

Thanks,

Jérémy

### CODE REVIEW

**Comment by slashfan** [comment]
Thanks :)

**Comment by JJK801** [comment]
my pleasure ;)

**Comment by JJK801** [comment]
can you push a tag plz?

**Comment by slashfan** [comment]
It's done.

**Comment by JJK801** [comment]
thanks :D

**Pull request merged**
