### PR TITLE
Update 3-functional-testing.md

### PR DESCRIPTION
**Pull request by MasseElch**
Typo in ssl-key-paths

### CODE REVIEW

**Comment by chalasr** [comment]
Good catch, thank you @MasseElch

**Comment by chalasr** [comment]
I just realize that this is wrong, the doc was correct. Keys should go in the `var/jwt` directory, not `app/var/jwt`. Reverting.

**Comment by chalasr** [comment]
See https://github.com/lexik/LexikJWTAuthenticationBundle/pull/319

**Comment by MasseElch** [comment]
The `var` directory will not go into git, but for our CI-Pipeline we created some keys only for testing purposes.

I thought this was your intention when you wrote the following lines for generating a testing key-pair:

```
$ openssl genrsa -out app/var/jwt/private-test.pem -aes256 4096
$ openssl rsa -pubout -in app/var/jwt/private-test.pem -out app/var/jwt/public-test.pem
```

**Comment by MasseElch** [comment]
Ah nevermind, you just did.

**Comment by chalasr** [comment]
@MasseElch Yeah, that's the mistake. `app` was the right place before symfony 3. Sorry for the noise and thanks again for pointing the error.

**Pull request merged**
