### PR TITLE
Improve user_identity_field deprecation message

### PR DESCRIPTION
**Pull request by Jean85**
As discovered in https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1051#issuecomment-1239327663

### CODE REVIEW

**Comment by Jean85** [comment]
This should fix #1051

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Works for me!

**Comment by chalasr** [comment]
Thanks ~~Jean~~ Alessandro! And sorry for the wtf moment!

**Comment by Jean85** [comment]
Thank you for the fast merge!

**Pull request merged**
