### PR TITLE
Configuration options modified

### PR DESCRIPTION
**Pull request by Spomky**
This PR modifies the following configuration option:
* the `encryption_algorithm` is renamed into `signature_algorithm`.
Documentation is updated accordingly.

This PR includes minor modifications on the service.xml file.

### CODE REVIEW

**Comment by Spomky** [comment]
@chalasr as discussed yesterday

**Comment by chalasr** [comment]
@Spomky I just opened #196 that make the `*_key_path` options nullable.

Sorry for that you worked on this here before. 
Fortunately it is not the only thing you did, the change from `encryption_algorithm` to `signature_algorithm` is legit to me 👍 .

Could you please revert the changes you did that are done by #196?
I'll properly review the rest of this and be back.

**Comment by chalasr** [comment]
Here are the changes that need to be reverted:

- [composer.json](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/195/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R32)
- [Configuration.php#L27](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/195/files#diff-850942b3ba24ab03a40aaa81b6152852L27)
- [Configuration.php#L30](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/195/files#diff-850942b3ba24ab03a40aaa81b6152852L30)
- [Configuration.php#L33](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/195/files#diff-850942b3ba24ab03a40aaa81b6152852L33) (It doesn't seem useful to me, if you think it is please just let me know why)
- [AbstractKeyLoader.php](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/195/files#diff-7bd055952a7b3ba56f5e6dd86e3e368dR1)

**Comment by Spomky** [comment]
Hi @chalasr 
I reverted my changes according to your previous comment.
Commits squashed.

**Comment by chalasr** [comment]
Thank you @Spomky.
Could you please review #196?

**Pull request merged**
