### PR TITLE
Add support of multiple public keys to verify tokens with a set of keys

### PR DESCRIPTION
**Pull request by alexandre-daubois**
It may be convenient to use multiple public keys to verify token signature when using RS algorithm. It would allow to verify tokens coming from different providers.

Somehow related to #707

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for the PR.
#707 is about allowing per-firewall configuration (including keys). Would that match your use case? Or do you need to support multiple keys for your entire application as this PR currently suggests?

**Comment by alexandre-daubois** [comment]
Thanks for your reply! I don't think this would match our use case. Indeed, we would need to support multiple public keys for a single firewall. Tokens are coming from many providers, each with their own key, passing to a single firewall on a common endpoint.

**Comment by HidouriAnis** [comment]
I currently have the same needs as you, what did you do as a solution?

**Comment by alexandre-daubois** [comment]
@HidouriAnis for now, we did it like as it's in #707, in [this comment](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/707#issuecomment-678762286). Even if this works, this is not super convenient to redefine all services like this. It's also very verbose.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @alexandre-daubois.

**Pull request merged**
