### PR TITLE
Make JWTManager::$userIdClaim nullable

### LINKED ISSUE #590: Cannot autowire service "Lexik\Bundle\JWTAuthenticationBundle\Services\JWT Manager": argument "$userIdClaim" of method "__construct()" has no type-hint , you should configure its value explicitly.
Cannot autowire service "Lexik\Bundle\JWTAuthenticationBundle\Services\JWT Manager": argument "$userIdClaim" of method "__construct()" has no type-hint , you should configure its value explicitly.

symfony 4 symfony/lts dev-master

lexik version v2.6.1

### PR DESCRIPTION
**Pull request by chalasr**
Fixes #590

### CODE REVIEW

**Comment by bricejulia** [comment]
Is this going to be released soon ?
Thanks

**Comment by chalasr** [comment]
Yes sorry, it will be released at the end of the week.

**Comment by ML-ThomasC** [comment]
Hi,
When will this fix be tagged ? The last tag is 2.6.1 and this fix is not inside it.
It is merge into master but not yet usable for alot of applications.

Thank you.

**Comment by chalasr** [comment]
Released in v2.6.2, apologies for the delay!

**Pull request merged**
