### PR TITLE
Allow lcobucci/jwt v5

### PR DESCRIPTION
**Pull request by maxhelias**

### CODE REVIEW

**Comment by maxhelias** [comment]
Humm lcobucci/jwt need php:^8; Maybe we can do this for version 3?

**Comment by chalasr** [comment]
How hard is it to support both v3 and v5? Ideally we'd let composer do its resolution job

**Comment by maxhelias** [comment]
@chalasr Actually, no, it's okay 😅

**Comment by chalasr** [comment]
Awesome!

**Comment by chalasr** [comment]
Thank you @maxhelias.

**Pull request merged**
