### PR TITLE
Fix for PHP <7.4 compatibility

### LINKED ISSUE #1182: Version 2.20+ requiring php 7.1 >= but using arrow functions
In the EnableEncryptionConfigCommand command you are using arrow functions (php 7.4 feature) and in composer are requiring PHP version >= 7.1

This is throwing an exception when installing the package on a PHP 7.2 environment

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/3df8317555ea899a81b5c6b7558e421838f2f926/composer.json#L40C15-L40C15

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/v2.20.2/Command/EnableEncryptionConfigCommand.php#L89

image

### PR DESCRIPTION
**Pull request by fracsi**
Follow up for #1174
Fixes #1182 
Arrow functions are introduced in php 7.4 as well.

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]

**Comment by chalasr** [comment]
Would you mind double-checking there is no more similar issues please?

**Review by chalasr — APPROVED** [review]

**Comment by fracsi** [comment]
@chalasr Found an another.
I ran throught the code with PHP 7.2 (min version for Symfony 5.4).
#1041 and #1167 introduced the incompatibilities.

I have no idea why the checks were green for PHP 7.2 and Symfony 5.4

**Comment by chalasr** [comment]
@fracsi Good question, it seems that build is totally broken despite it doesn't show up as such!
https://github.com/lexik/LexikJWTAuthenticationBundle/actions/runs/7107317672/job/19348521987
Gonna look into this asap.

**Comment by chalasr** [comment]
Good catch, thanks @fracsi.

**Pull request merged**
