### PR TITLE
Fix ci 3x

### PR DESCRIPTION
**Pull request by Spomky**
Base on #1201 
/cc @chalasr

### CODE REVIEW

**Comment by Spomky** [comment]
I spotted deprecation inconstistencies I need to fix first.
Stay tuned.

**Comment by Spomky** [comment]
Looks good now.
Tests pass and no direct deprecation notices.

**Comment by chalasr** [comment]
Whoop whoop 🙌 Thanks!

**Comment by chalasr** [comment]
Thanks a lot @Spomky!

**Pull request merged**
