### PR TITLE
#1083. Fixed issue with option user_id_claim.

### PR DESCRIPTION
**Pull request by koftikes**
Fixed issue with configuration option `user_id_claim`

### CODE REVIEW

**Comment by chalasr** [comment]
Would you mind adding a testcase covering this change ? Happy to provide some guidance if needed

**Comment by koftikes** [comment]
Yes, please. 
What exactly test case you want to see?
in issue 1083(https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1083) exist example.

**Comment by koftikes** [comment]
@chalasr Hello. Any additional info?

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
The patch looks good, I'll add the test on my own. Thanks a lot @koftikes

**Comment by chalasr** [comment]
Thank you @koftikes.

**Pull request merged**
