### PR TITLE
Changed `JWTAuthenticator::start` method return type to more generic `Response` type

### LINKED ISSUE #904: New JWTAuthenticator::start method requires hard return type of JWTAuthenticationFailureResponse
The new Symfony 5.3 `JWTAuthenticator::start` method has the return type of `JWTAuthenticationFailureResponse` when the event and all other methods require Symfony Response object. This breaks if your event subscribers set custom responses.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/06bd43f8aed787186e598aeb89be4c0dc2727650/Security/Authenticator/JWTAuthenticator.php#L75

### PR DESCRIPTION
**Pull request by aurimasniekis**
Not a big change just fixes an issue where the old code is upgraded to use the new JWTAuthenticator.

This fixes #904

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by aurimasniekis** [comment]
I am not sure about`5.4@dev`build, I don't really see how is it related to my change.

**Comment by chalasr** [comment]
Don’t worry about it, it’s not related

**Comment by chalasr** [comment]
Thanks for fixing this bug @aurimasniekis.

**Comment by fd6130** [comment]
Just encounter this issue on today. I think this patch should be release as soon as possible otherwise it break current project that have custom response. 

How do you think?  @chalasr

**Comment by chalasr** [comment]
Thanks for the ping! I will draft the release tonight

**Pull request merged**
